# -*- coding: utf-8 -*-
"""Doc-Genie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JXUFTbEOASqHgzEOWRsmRsVI_e1Y5SK
"""

!pip install reportlab

!pip install reportlab

import ast
import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import tempfile

class DocGenieAnalyzer:

    @staticmethod
    def extract_function_signature(code):
        tree = ast.parse(code)

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):

                name = node.name
                params = []

                for arg in node.args.args:
                    params.append({
                        "name": arg.arg,
                        "type": "Any",
                        "default": None
                    })

                return_type = "Any"

                return {
                    "name": name,
                    "params": params,
                    "return_type": return_type,
                    "node": node
                }

    @staticmethod
    def analyze_function_logic(func_node):

        analysis = {
            "has_loops": False,
            "has_conditions": False,
            "operations": [],
            "function_calls": []
        }

        for node in ast.walk(func_node):

            if isinstance(node, (ast.For, ast.While)):
                analysis["has_loops"] = True

            if isinstance(node, ast.If):
                analysis["has_conditions"] = True

            if isinstance(node, ast.BinOp):
                analysis["operations"].append(type(node.op).__name__)

            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    analysis["function_calls"].append(node.func.id)

        return analysis

    @staticmethod
    def generate_google_docstring(signature, analysis):

        doc = '"""\n'
        doc += f"{signature['name']} function.\n\n"

        if analysis["has_conditions"]:
            doc += "Contains conditional logic.\n"

        if analysis["has_loops"]:
            doc += "Uses loop operations.\n"

        doc += "\nArgs:\n"

        for p in signature["params"]:
            doc += f"    {p['name']} ({p['type']}): parameter description\n"

        doc += "\nReturns:\n"
        doc += f"    {signature['return_type']}: result value\n"

        doc += '"""\n'

        return doc

    @staticmethod
    def generate_numpy_docstring(signature, analysis):

        doc = '"""\n'
        doc += f"{signature['name']} function.\n\n"

        doc += "Parameters\n"
        doc += "----------\n"

        for p in signature["params"]:
            doc += f"{p['name']} : {p['type']}\n"
            doc += "    parameter description\n"

        doc += "\nReturns\n"
        doc += "-------\n"
        doc += f"{signature['return_type']}\n"
        doc += "    result value\n"

        doc += '"""\n'

        return doc


def process_code(code, style):

    sig = DocGenieAnalyzer.extract_function_signature(code)
    analysis = DocGenieAnalyzer.analyze_function_logic(sig["node"])

    if style == "google":
        doc = DocGenieAnalyzer.generate_google_docstring(sig, analysis)
    else:
        doc = DocGenieAnalyzer.generate_numpy_docstring(sig, analysis)

    lines = code.split("\n")

    for i, line in enumerate(lines):
        if line.strip().startswith("def"):
            lines.insert(i+1, "    " + doc.replace("\n", "\n    "))
            break

    return "\n".join(lines)


def export_txt(text):

    path = tempfile.mktemp(".txt")
    with open(path, "w") as f:
        f.write(text)

    return path


def export_pdf(text):

    path = tempfile.mktemp(".pdf")

    styles = getSampleStyleSheet()
    story = [Paragraph(line, styles["Normal"]) for line in text.split("\n")]

    doc = SimpleDocTemplate(path)
    doc.build(story)

    return path


with gr.Blocks() as demo:

    gr.Markdown("# Doc-Genie Python Docstring Generator")

    code_input = gr.Textbox(
        label="Enter Python Function",
        lines=15,
        value="""def add(a,b):
    return a+b"""
    )

    style = gr.Radio(
        ["google","numpy"],
        value="google",
        label="Docstring Style"
    )

    generate_btn = gr.Button("Generate Docstring")

    output = gr.Code(label="Output Code")

    txt_btn = gr.Button("Download TXT")
    pdf_btn = gr.Button("Download PDF")

    txt_file = gr.File()
    pdf_file = gr.File()

    generate_btn.click(
        process_code,
        inputs=[code_input,style],
        outputs=output
    )

    txt_btn.click(export_txt,inputs=output,outputs=txt_file)

    pdf_btn.click(export_pdf,inputs=output,outputs=pdf_file)


demo.launch()